Work on login page hooking up with backend auth
redacademy/mvmnt-lab-fall-2018 pull request #32
Opened 2018-12-05 23:33 UTC by vbertoletti

Please note that this feature is not complete, we just need this PR in order for other people to work on their components as well, since I've added config/api.js and have fixed the file structure.

2018-12-05 23:53 UTC, siddharthparmar7 requested changes
Your branch is not following the convention we agreed on. Branch name should not start with block letters.

Your project throws an error.

Please make the required changes. Thank you.

2018-12-05 23:53 UTC, siddharthparmar7 commented on client/js/App.js
> +import client from "../config/api";
Since you changed your project structure it's throwing errors now. Please make sure all of your imports exports are correct.

2018-12-05 23:53 UTC, siddharthparmar7 commented on client/js/screens/LogIn/LogIn.js
> +  console.log("res",res)
remove this console log

2018-12-05 23:53 UTC, siddharthparmar7 commented on client/js/screens/LogIn/LogIn.js
> +          height: "100%"
use styles.js file for all of your styles and use resize mode or Dimensions or flexbox. Try avoiding height and width 100%.

2018-12-05 23:53 UTC, siddharthparmar7 commented on client/js/screens/LogIn/LogIn.js
> +        <View>
Should not have a View component. by itself. Use Fragment instead.

2018-12-05 23:53 UTC, siddharthparmar7 commented on client/js/screens/LogIn/LogIn.js
> +              <View>
same as above.

2018-12-05 23:53 UTC, siddharthparmar7 commented on client/js/screens/LogIn/LogIn.js
> +                <TouchableOpacity>
do you have a call back function for this?

2018-12-05 23:53 UTC, siddharthparmar7 commented on client/js/screens/LogIn/LogIn.js
> +                <TouchableOpacity style={styles.button}>
same here. Do you have a callback function for this?

2018-12-05 23:53 UTC, siddharthparmar7 commented on client/js/screens/LogIn/LogInContainer.js
> +import { Text, View } from "react-native";
remove unnecessary components being imported.

2018-12-05 23:53 UTC, siddharthparmar7 commented on client/js/screens/LogIn/LogInContainer.js
> +            {console.log("token coming here", data)}
remove the console log.

2018-12-05 23:53 UTC, siddharthparmar7 commented on client/js/screens/LogIn/LogInContainer.js
> +    );
you should not have images in the screen dir. move them to assets dir if you need them.

2018-12-05 23:53 UTC, siddharthparmar7 commented on client/js/screens/LogIn/styles.js
> +  container: globalStyles.container,
use Dimensions / resizemode for height, width. Use flexbox to avoid having huge margins/paddings like 50.

2018-12-05 23:53 UTC, siddharthparmar7 commented on mvmnt-lab-api/package.json
> +>>>>>>> commit changes before pulling from develop
merge conflicts? Please resolve them.

2018-12-07 17:57 UTC, 10thfloor approved these changes

2018-12-07 17:57 UTC, merged