Initial work on profile page
redacademy/mvmnt-lab-fall-2018 pull request #35
Opened 2018-12-06 23:15 UTC by vbertoletti

Add profile page markup and some styles so it'll be easier once fetching data from backend.

2018-12-07 17:30 UTC, 10thfloor reviewed
Hey Vanessa. Not sure what happened, but there are a lot of unresolved merges in your code. Be careful not to commit code that is unmerged!

2018-12-07 17:30 UTC, 10thfloor commented on client/js/screens/About/styles.js
> +<<<<<<< HEAD
Oops. You missed these merge markers.

2018-12-07 17:30 UTC, 10thfloor commented on client/js/screens/LogIn/LogIn.js
> +export default Login;
Looks great! Nice job on the Final Form implementation.

2018-12-07 17:30 UTC, 10thfloor commented on client/js/screens/Profile/Profile.js
> +<<<<<<< HEAD
More merge markers. Remove these carefully.

2018-12-07 17:30 UTC, 10thfloor commented on client/js/screens/Profile/ProfileContainer.js
> +<<<<<<< HEAD
Merge markers in your code.

2018-12-07 17:30 UTC, 10thfloor commented on mvmnt-lab-api/package.json
> +<<<<<<< HEAD
Merge markers.

2018-12-07 17:31 UTC, 10thfloor requested changes
Remove all unmerged code.

2018-12-10 02:42 UTC, vbertoletti commented
Hi Mack, conflicts and page improvements should be ok now for your next review. 
Thanks!

2018-12-11 21:13 UTC, 10thfloor approved these changes

2018-12-11 21:13 UTC, merged