Fix all bugs on login and logout
redacademy/mvmnt-lab-fall-2018 pull request #67
Opened 2018-12-12 20:01 UTC by vbertoletti

This PR fixes bugs on login screen, profile screen and realm/user provider, as they are all connected to login and logout. Profile page renders data from db without errors.

2018-12-13 19:16 UTC, siddharthparmar7 requested changes
I can not check your app because it throws an error Unable to resolve module `../screens/Login` from root stack navigation. Please fix it. Also, you should be calling your dirs, files and components SignIn and SignUp, not LogIn and SignUp. Please make the changes. Thank you.

2018-12-13 19:16 UTC, siddharthparmar7 commented on client/js/screens/LogIn/LogInContainer.js
> +              if (token.length > 0) {
if you make your Context state null initially you will not have to check for your token's length. You can just do `if(token)`

2018-12-13 19:16 UTC, siddharthparmar7 commented on client/js/screens/LogIn/LogInContainer.js
> +                );
add prop type validation.

2018-12-13 19:16 UTC, siddharthparmar7 commented on client/js/screens/Profile/ProfileContainer.js
> +    );
please add prop type validations.

2018-12-13 19:16 UTC, siddharthparmar7 commented on client/js/screens/Profile/Profile.js
>          <Text style={styles.buttonText}>LOGOUT</Text>
add prop type validation.

2018-12-14 18:58 UTC, vbertoletti commented
Fixed all requirements, thanks.

2018-12-14 19:32 UTC, siddharthparmar7 requested changes
Please resolved all the issues. Thank you.

2018-12-14 19:32 UTC, siddharthparmar7 commented on client/js/context/UserContext/UserProvider.js
>        id: ""
make this null too.

2018-12-14 19:32 UTC, siddharthparmar7 commented on client/js/context/UserContext/UserProvider.js
> +        this.setState({ id: "", token: null });
id should be null too.

2018-12-14 19:32 UTC, siddharthparmar7 commented on client/js/screens/Profile/Profile.js
> +  id: PropTypes.string
the props that are not required, you should have default props for them.

2018-12-14 19:32 UTC, siddharthparmar7 commented on client/js/screens/Profile/ProfileContainer.js
> +    );
Please resolve this.

2018-12-14 19:32 UTC, siddharthparmar7 commented on client/js/screens/SignIn/SignIn.js
>        <StatusBar barStyle="light-content" />
make all your View components Fragment that is just by themselves.

2018-12-14 19:32 UTC, siddharthparmar7 commented on client/js/screens/SignIn/SignIn.js
> +  storeSessionToken: PropTypes.func
add default props if these props are not required.

2018-12-14 19:32 UTC, siddharthparmar7 commented on client/js/screens/LogIn/LogInContainer.js
> +                );
this is not resolved yet.

2018-12-14 21:28 UTC, vbertoletti commented
Amended proptypes as required, id initial state is now null, also added fragment to one section that was wrapped in unnecessary view tag, fixed LogInContainer to be SignInContainer.

2018-12-14 21:37 UTC, siddharthparmar7 requested changes
Please make the requested changes and don't validate your function arguments. Validate your props.

2018-12-14 21:37 UTC, siddharthparmar7 commented on client/js/context/UserContext/UserProvider.js
> +        this.setState({ id: "", token: null });
ID is not null here.

2018-12-14 21:37 UTC, siddharthparmar7 commented on client/js/screens/Profile/ProfileContainer.js
> +  data: null
these are not props. They are function arguments. 

the only prop here is navigation.

2018-12-14 21:37 UTC, siddharthparmar7 commented on client/js/screens/SignIn/SignInContainer.js
> +  token: null
these are not props. these are function arguments.

You should have all of your prop validations with .isRequired and if they are not required only then have default props.

2018-12-14 22:17 UTC, vbertoletti commented
Thanks for taking the time to clarify, I have pushed more changes. Please let me know if something needs improvements.

2018-12-18 00:18 UTC, siddharthparmar7 approved these changes
Thank you!

2018-12-18 00:18 UTC, merged