Style & Setup Poses Screen
redacademy/mvmnt-lab-fall-2018 pull request #68
Opened 2018-12-12 23:00 UTC by EmilioLombana

2018-12-14 18:36 UTC, siddharthparmar7 requested changes
Please make the requested changes. Thank you

2018-12-14 18:36 UTC, siddharthparmar7 commented on client/js/App.js
>  import AppNavigator from "./navigation/RootStackNavigator";
remove unnecessary imports.

2018-12-14 18:36 UTC, siddharthparmar7 commented on client/js/screens/Poses/Poses.js
> +      style={{
all the styles should be in your styles.js file

2018-12-14 18:36 UTC, siddharthparmar7 commented on client/js/screens/Poses/Poses.js
> +  _keyExtractor = item => item.id;
why _? did you mean to create a const?

2018-12-14 18:36 UTC, siddharthparmar7 commented on client/js/screens/Poses/Poses.js
> +              {console.log(item.icon)}
remove all the console logs.

2018-12-14 18:36 UTC, siddharthparmar7 commented on client/js/screens/Poses/Poses.js
> +              {console.log(item.icon)}
remove this console log

2018-12-14 18:36 UTC, siddharthparmar7 commented on client/js/screens/Poses/PosesContainer.js
> +          if (loading)
what if there is an error?

2018-12-14 18:36 UTC, siddharthparmar7 commented on client/js/screens/Poses/styles.js
> +    right: 20
we do not use left and right properties. Please use flexbox.

2018-12-14 18:36 UTC, siddharthparmar7 commented on client/js/screens/Poses/Poses.js
> +  Superbug: require("../../assets/images/icons/Superbug.png")
this is a good way to do it. Can you put all of your images here for this file?

2018-12-14 18:36 UTC, siddharthparmar7 commented on client/js/screens/Poses/Poses.js
>  };
prop type validation for data?

2018-12-17 17:20 UTC, 10thfloor approved these changes

2018-12-18 23:21 UTC, 10thfloor commented
CLosing this. Not sure what happened here.

2018-12-18 23:21 UTC, closed without merging